// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhocQtRhPYY2_fNEl4b1Ny2qlMiNsgKkQ',
    appId: '1:857781852543:web:f4d337a372a1c4be4aa24a',
    messagingSenderId: '857781852543',
    projectId: 'fir-app-e9a63',
    authDomain: 'fir-app-e9a63.firebaseapp.com',
    storageBucket: 'fir-app-e9a63.firebasestorage.app',
    measurementId: 'G-KC93VLJ0CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdzBY5eOU64V3ozfV_AEQ16A1PrywkSXE',
    appId: '1:857781852543:android:9f9d68b0d01f796a4aa24a',
    messagingSenderId: '857781852543',
    projectId: 'fir-app-e9a63',
    storageBucket: 'fir-app-e9a63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGWPxWyqmGeDKJIRChtV-XKuivEfkHA6o',
    appId: '1:857781852543:ios:4618a416398e39f94aa24a',
    messagingSenderId: '857781852543',
    projectId: 'fir-app-e9a63',
    storageBucket: 'fir-app-e9a63.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGWPxWyqmGeDKJIRChtV-XKuivEfkHA6o',
    appId: '1:857781852543:ios:4618a416398e39f94aa24a',
    messagingSenderId: '857781852543',
    projectId: 'fir-app-e9a63',
    storageBucket: 'fir-app-e9a63.firebasestorage.app',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhocQtRhPYY2_fNEl4b1Ny2qlMiNsgKkQ',
    appId: '1:857781852543:web:677626ec5efab57f4aa24a',
    messagingSenderId: '857781852543',
    projectId: 'fir-app-e9a63',
    authDomain: 'fir-app-e9a63.firebaseapp.com',
    storageBucket: 'fir-app-e9a63.firebasestorage.app',
    measurementId: 'G-3XF5S1829V',
  );

}